[package]
name = "simply_firewall"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
tokio = { version = "1.37.0", features = ["full"] }
sea-orm = { version = "1.0.0", features = ["sqlx-sqlite", "runtime-tokio-rustls", "macros", "with-uuid", "with-chrono"] }
sea-orm-migration = { version = "1.0.0", features = ["runtime-tokio-rustls", "sqlx-sqlite"] }
ipnetwork = "0.20.0"
axum-client-ip = "0.6.0"
reqwest = { version = "0.12.4", default-features = false, features = ["json", "rustls-tls"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "fmt"] }
serde = { version = "1.0.200", features = ["derive"] }
serde_json = "1.0.116"
uuid = { version = "1.8.0", features = ["v4", "serde"] }
chrono = { version = "0.4.38", features = ["serde"] }
sha2 = "0.10.8"
tower-http = { version = "0.5.2", features = ["fs", "trace"] }
hex = "0.4.3"
rand = "0.8.5"
thiserror = "1.0.61"
dotenvy = "0.15.7"
